/// <reference types= “cypress”>

beforeEach (() => {
  cy.viewport(1280, 1024)
  cy.setCookie("mal_consent_gdpr_analytical","t")
  cy.visit("https://mall.sk")
  })    

describe("mall.sk Search Button", () => {

  it("Classic Search in the Search Button", () => {
    cy.log("Find Search Button and Type okuliare")
     cy.get("[data-sel='search-input']")
       .type("okuliare")
    cy.log("Autocomplete Suggestions should be visible")
     cy.get(".search-category__title")
       .should("be.visible")
       .should("contain.text","okuliare")
    cy.log("Enter Search Button")
     cy.get("[data-sel='search-input']")
       .click()
       .type('{enter}')
    cy.log("Close Catalog Offer")
     cy.get(".l-exponea-close-cross")
        .eq("0")
        .should("be.visible")
        .click()
        .should("not.be","visible")
    cy.log("Verify Url")
      cy.url()
        .should("include","okuliare")
    cy.log("Verify Results")
      cy.get(".category-products")
        .should("be.visible")
        .should("contain.text","okuliare")
    })  
 
    it("Case Sensitivity", () => {
      cy.log("Find Search Button and Type OKULIARE")
       cy.get("[data-sel='search-input']")
         .type("OKULIARE")
      cy.log("Autocomplete Suggestions should be visible")
       cy.get(".search-category__title")
         .should("be.visible")
         .should("contain.text","okuliare")
      cy.log("Enter Search Button")
       cy.get("[data-sel='search-input']")
         .click()
         .type('{enter}')
      cy.log("Close Catalog Offer")
       cy.get(".l-exponea-close-cross")
          .eq("0")
          .should("be.visible")
          .click()
          .should("not.be","visible")
      cy.log("Verify Url")
        cy.url()
          .should("include","OKULIARE")
      cy.log("Verify Results")
        cy.get(".category-products")
          .should("be.visible")
          .should("contain.text","okuliare")
      })  
 
      it("Autocomplete Verification", () => {
        cy.log("Find Search Button and Type okulia")
         cy.get("[data-sel='search-input']")
           .type("okulia")
        cy.log("Autocomplete Suggestions should be visible")
         cy.get(".search-category__title")
           .should("be.visible")
           .should("contain.text","okuliare")
        cy.log("Enter Search Button")
         cy.get("[data-sel='search-input']")
           .click()
           .type('{enter}')
        cy.log("Close Catalog Offer")
         cy.get(".l-exponea-close-cross")
            .eq("0")
            .should("be.visible")
            .click()
            .should("not.be","visible")
        cy.log("Verify Url")
          cy.url()
            .should("include","okulia")
        cy.log("Verify Results")
          cy.get(".category-products")
            .should("be.visible")
            .should("contain.text","okuliare")
        })  

        it("Non-Existent Word in Page", () => {
          cy.log("Find Search Button and Type ovolsecujutsixeen")
           cy.get("[data-sel='search-input']")
             .type("ovolsecujutsixeen")
          cy.log("Autocomplete Suggestions should not be visible")
           cy.get(".search-category__title")
             .should("not.be","visible")
          cy.log("Enter Search Button")
           cy.get("[data-sel='search-input']")
             .click()
             .type('{enter}')
          cy.log("Close Catalog Offer")
           cy.get(".l-exponea-close-cross")
              .eq("0")
              .should("be.visible")
              .click()
              .should("not.be","visible")
          cy.log("Verify Url")
            cy.url()
              .should("include","ovolsecujutsixeen")
          cy.log("Verify No Results")
            cy.contains("Pre daný výber neboli nájdené žiadne ponúkané výrobky.")
              .should("be.visible")
          })  
  

 
  })
